Create a LifeOmic org README.md
lifeomic/.github pull request #9
Opened 2021-11-17 20:06 UTC by hemp

2021-11-17 20:11 UTC, ynotdraw submitted a review, later dismissed

2021-11-17 20:58 UTC, bishopb requested changes

2021-11-17 20:58 UTC, bishopb commented on profile/README.md
> +* [Website](https://lifeomic.com/)
Request for a security plug:

```
* [Security](https://security.lifeomic.com/)
```

2021-11-17 21:05 UTC, smolster reviewed
so awesome

2021-11-17 21:05 UTC, smolster commented on profile/README.md
> +LifeOmic's platform spans the health continuum of care from prevention and wellness to diagnosis, management, treatment and research.
```suggestion
LifeOmic's platform spans the continuum of health care from prevention and wellness to diagnosis, management, treatment and research.
```

2021-11-18 13:29 UTC, ynotdraw approved these changes

2021-11-18 13:42 UTC, smolster approved these changes

2021-11-18 16:09 UTC, bishopb approved these changes

2021-11-18 18:04 UTC, merged